name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux-64:
    name: Build on Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build Executable
        # --add-data "SOURCE_PATH:DEST_PATH_IN_BUNDLE" for Linux/macOS
        run: pyinstaller --onefile --noconfirm --add-data "assets:assets" main.py
      - name: Rename Executable
        run: mv dist/main dist/compapet-linux-64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compapet-linux-64
          path: dist/compapet-linux-64

  build-linux-32:
    name: Build on Linux x86_32
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build Executable
        # --add-data "SOURCE_PATH:DEST_PATH_IN_BUNDLE" for Linux/macOS
        run: pyinstaller --onefile --noconfirm --add-data "assets:assets" main.py
      - name: Rename Executable
        run: mv dist/main dist/compapet-linux-32
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compapet-linux-32
          path: dist/compapet-linux-32

  build-linux-arm-64:
    name: Build on Linux ARM 64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build Executable
        # --add-data "SOURCE_PATH:DEST_PATH_IN_BUNDLE" for Linux/macOS
        run: pyinstaller --onefile --noconfirm --add-data "assets:assets" main.py
      - name: Rename Executable
        run: mv dist/main dist/compapet-linux-arm-64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compapet-linux-arm-64
          path: dist/compapet-linux-arm-64

  build-linux-armhf-32:
    name: Build on Linux ARMHF 32
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build Executable
        # --add-data "SOURCE_PATH:DEST_PATH_IN_BUNDLE" for Linux/macOS
        run: pyinstaller --onefile --noconfirm --add-data "assets:assets" main.py
      - name: Rename Executable
        run: mv dist/main dist/compapet-linux-armhf-32
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compapet-linux-armhf-32
          path: dist/compapet-linux-armhf-32

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build Executable
        # --add-data "SOURCE_PATH;DEST_PATH_IN_BUNDLE" for Windows (note semicolon)
        run: pyinstaller --onefile --noconfirm --add-data "assets;assets" main.py
      - name: Rename Executable
        run: Rename-Item -Path dist\main.exe -NewName compapet-windows.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compapet-windows
          path: dist/compapet-windows.exe

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build Executable
        # --add-data "SOURCE_PATH:DEST_PATH_IN_BUNDLE" for Linux/macOS
        run: pyinstaller --onefile --noconfirm --add-data "assets:assets" main.py
      - name: Rename Executable
        run: mv dist/main dist/compapet-macos
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compapet-macos
          path: dist/compapet-macos

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-linux-64, build-linux-32, build-linux-arm-64, build-linux-armhf-32, build-windows, build-macos]
    steps:
      - name: Download Linux x86_64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: compapet-linux-64
          path: ./release
      - name: Download Linux x86_32 Artifact
        uses: actions/download-artifact@v4
        with:
          name: compapet-linux-32
          path: ./release
      - name: Download Linux ARM 64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: compapet-linux-arm-64
          path: ./release
      - name: Download Linux ARMHF 32 Artifact
        uses: actions/download-artifact@v4
        with:
          name: compapet-linux-armhf-32
          path: ./release
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: compapet-windows
          path: ./release
      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: compapet-macos
          path: ./release
      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/compapet-linux-64
            release/compapet-linux-32
            release/compapet-linux-arm-64
            release/compapet-linux-armhf-32
            release/compapet-windows.exe
            release/compapet-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}